require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/resque/failure/email_notification.rb'
Rails/PluckId:
  Enabled: true
Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/resque.rake'
Rails/SkipsModelValidations:
  Exclude:
    - 'test/**/*.rb'

Style/ArrayCoercion:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringLiterals:
  Exclude:
    - 'config/importmap.rb'
Style/SymbolArray:
  EnforcedStyle: brackets
